### ISSUE TITLE
npm install errors

### ISSUE THREAD

**Issue by BaileyTrotter** [MotherTongues/mothertongues-UI-Web#10]
I get a series of errors each time I run `npm install` that I'm not sure how to resolve. 

Here's a screenshot of them:

<img width="584" alt="Screen Shot 2023-01-21 at 2 31 32 PM" src="https://user-images.githubusercontent.com/96272684/213895068-60722d9a-6b2e-496d-8632-5403301183e4.png">

If I keep going and following the next steps on the guides the dictionary runs fine locally. So, I update `config.js` and `dict_cached.js`, then run `npm start`.

<img width="1188" alt="Screen Shot 2023-01-21 at 3 11 18 PM" src="https://user-images.githubusercontent.com/96272684/213895261-ccfc7fe9-aefa-401b-8a44-a6b33bc79c43.png">

When I try to commit the changes to github, the deploy fails or only the README file is published. 

<img width="1067" alt="Screen Shot 2023-01-21 at 4 36 25 PM" src="https://user-images.githubusercontent.com/96272684/213895399-26443ea1-6ab6-4981-ba71-8444f4f9326d.png">

Do you know if there's anything I'm doing wrong?

-Bailey

**Comment by roedoejet** [comment]
Hi @BaileyTrotter - is this issue still open or did you resolve it? I see your build seems like it's passing - if it's fixed, can you post the solution? Thanks!

**Comment by BaileyTrotter** [comment]
Hi @roedoejet the issue that I am still having is that README file is being published on github pages instead of the dictionary (and it has been since the original fork). 

I had some help figuring out how to get the build to pass. I think what we ended up doing was adding in ssh key, and used the latest James Ives v4 deploy. I believe the changes can be seen here: [https://github.com/BaileyTrotter/mothertongues-UI-Web/commit/03c94794c7403ea60a53db1184ead74077621176]().

**Comment by roedoejet** [comment]
Sounds like maybe your GitHub Pages isn't building from the `gh-pages` branch. Try changing it by doing this:

![image](https://user-images.githubusercontent.com/14815080/214456091-09d9ad63-de0d-41ef-b6bd-c101150a0afc.png)

**Comment by BaileyTrotter** [comment]
That was it! I think I had the exact same issue before (oops). Thank you!

**Comment by roedoejet** [comment]
no worries - happy it's working!
