### ISSUE TITLE
Adding audio files

### ISSUE THREAD

**Issue by BaileyTrotter** [MotherTongues/mothertongues-UI-Web#17]
Hi @roedoejet 

I want to start adding audio files to the web-ui, but I can’t seem to figure out where to put them. I’ve added a file path for audio in one entry in `dict_cached.js`. The dictionary will show as if that entry has audio, but when clicked I get the message “couldn't find file named at path”. Is there a specific place in the repo that it would make the most sense for me to add a folder of all the audio files? Right now I just have one test audio file in projects/mtd/src/assets/duck.wav.

Thank you!
-Bailey

**Comment by roedoejet** [comment]
Good question! You need to add an `audio_path` key to the config file. You can do that in the MTD config.json file and it will copy over for you. I've added it here: https://github.com/BaileyTrotter/mothertongues-UI-Web/commit/f48b6e0f99d8e98a8477d853e91ac73d37f07d8c - I also just realized that the filename was `..duck.wav` but it should be just `duck.wav` maybe you were just troubleshooting. Anyways, I updated that [here](https://github.com/BaileyTrotter/mothertongues-UI-Web/commit/550fccb0d4cd6bcc6d43c8674d36a4d5e495bea5) too.

As for the right spot, the assets folder is correct! You might want to create a new folder called `audio` or something just to keep it cleaner. It which case you would change `audio_path` to `https://baileytrotter.github.io/mothertongues-UI-Web/assets/audio`.

Let me know if you have any other questions!

**Comment by BaileyTrotter** [comment]
Thank you! That is super helpful (as always).  

I also wanted to add a few images throughout the text on the 'About' page. Is that possible? Would I add an `image_path` in the config file too?

**Comment by roedoejet** [comment]
Good question - the images in the about page are actually added here: `https://github.com/MotherTongues/mothertongues-UI-Web/blob/master/projects/mtd/src/config/config.ts` in the config file. Each contributor can have an image associated with them. Just make `img` the path to your image (i.e. `https://path/to/your/img.png`). If you want to make other changes to the about page, you'll have to update the About component directly: https://github.com/MotherTongues/mothertongues-UI-Web/blob/master/projects/mtd/src/app/pages/about/about/about.component.html

**Comment by BaileyTrotter** [comment]
Perfect. Thank you!
